#!/bin/bash

SCRIPT_NAME=$(basename $0)
ROOT_FOLDER="$(dirname `dirname $0`)"
DOMAIN_FOLDER=${1:-$ROOT_FOLDER}
DOMAIN_FOLDER=${DOMAIN_FOLDER%/}
SCRIPT_REF="$(echo ${DOMAIN_FOLDER#$ROOT_FOLDER/} | sed 's/[^\/]*/../g')/utils/${SCRIPT_NAME}"

function generate {
  local type=$1
  echo "### $type Features"
  for feature in $(find $DOMAIN_FOLDER -name '*.feature' | grep -i "/$type/" | awk -F/ '{print $NF,$0}' | sort | cut -f2- -d' ')
  do
    desc=$(awk '/Feature:/ {gsub(/Feature: +/,"")} /Background:/ || /Scenario:/ || /^ *@/ {exit;} {gsub(/  +/,""); DESC=DESC" "$0} END{print DESC}' $feature)
    link=$(echo ${feature#$DOMAIN_FOLDER/} | awk -F"[/\.]" '{print "[`"$(NF-1)"`]("$0")"}')

    echo " * ${link}: $desc"
  done
  echo
}

echo "# Features"
echo "<!-- This has been automatically generated by [\`${SCRIPT_NAME}\`](${SCRIPT_REF}) -->"
echo
generate "Command"
generate "Query"
